[profile.default]
src = "contracts"
out = "forge_out"
libs = ["lib", "node_modules"]
remappings = [
  "@openzeppelin/contracts=node_modules/@openzeppelin/contracts",
  "forge-std=lib/forge-std/src"
]
 
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
 
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }